apiVersion: v1
kind: Service
metadata:
  name: sdc-elasticsearch
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: transport-protocol
  selector:
    app: sysdigcloud
    role: elasticsearch
---    
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sdc-elasticsearch 
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
spec:
  serviceName: sdc-elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: sysdigcloud
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: elasticsearch
    spec:
      initContainers:
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
        - name: elasticsearch
          #image: quay.io/sysdig/elasticsearch:5.1.1
          image: yofti/elasticsearch:5.5.3
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - IPC_LOCK  
                - SYS_RESOURCE  
          resources:
            requests:
              cpu: "2000m"
              memory: 4Gi
            limits:
              cpu: "4000m"
              memory: 8Gi              
          env:
            - name: ELASTICSEARCH_SERVICE
              value: sdc-elasticsearch
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: sysdigcloud
            - name: ELASTICSEARCH_MINIMUM_MASTER_NODES
              value: "2"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.jvm.options
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: gce-pd
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 40Gi
