kind: Pod
apiVersion: v1
metadata:
  name: sdc-backup-server
  namespace: sysdigcloud
  labels:
    name: sdc-backup-server
spec:
  containers:
    - name: sdc-backup-server
      image: yofti/ubuntu:latest
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: "/mnt/cassandra-backups"
        name: cassandra-backups
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  volumes:
    - name: cassandra-backups
      persistentVolumeClaim:
       claimName: cassandra-backups
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cassandra-backups
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
