kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: required-access-sysdig
rules:
  - apiGroups: ["extensions",""]
    resources: ["nodes","namespaces","pods","replicationcontrollers","services","events"]
    verbs: ["get","list","watch"]
  - nonResourceURLs: ["/healthz", "/healthz/*"]
    verbs: ["get"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system-default-service-account
subjects:
  - kind: ServiceAccount
    namespace: sysdigcloud
    name: default 
roleRef:
  kind: ClusterRole
  name: required-access-sysdig
  apiGroup: rbac.authorization.k8s.io
