apiVersion: v1
kind: Service
metadata:
  name: sdc-collector
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: collector
spec:
  type: LoadBalancer
  ports:
    - port: 6443
      name: secure-collector
      targetPort: 6443
  selector:
    app: sysdigcloud
    role: collector