apiVersion: v1
kind: Service
metadata:
  name: sdc-api
  namespace: sysdigcloud
  labels:
    app: sysdigcloud
    role: api
spec:
  type: LoadBalancer
  ports:
    - port: 443
      name: secure-api
      targetPort: 443
  selector:
    app: sysdigcloud
    role: api